export const DISPATCH_TEMPLATES = {
    etp_engenharia: {
        title: "Despacho – Dispensa/Elaboração de ETP (Engenharia)",
        template: (data) => `Trata-se de demanda referente à contratação de empresa especializada para execução de serviços de engenharia voltados à ${data.objeto || "[OBJETO]"}, conforme Documento de Formalização de Demanda e planilha orçamentária anexa.\n\nVerifica-se que o objeto contempla serviços de natureza predominantemente padronizada, com composições baseadas em referenciais técnicos oficiais (SINAPI, CDHU e FDE), abrangendo intervenções corretivas e preventivas em edificações existentes.\n\nNos termos do art. 41, inciso II, alínea "c", do Decreto Municipal nº 2.979/2024, a elaboração do Estudo Técnico Preliminar poderá ser dispensada mesmo em se tratando de serviço de engenharia, desde que demonstrado nos autos que sua não elaboração não comprometerá a aferição dos padrões de desempenho e qualidades almejadas.\n\nEncaminha-se à Secretaria Requisitante para manifestação expressa quanto à dispensa do ETP ou sua elaboração em até ${data.prazo || "3"} dias úteis.`,
    },
    validacao_cotacao: {
        title: "Despacho – Validação de Cotações pelas Secretarias",
        template: (data) => `Considerando as cotações encaminhadas para análise, a(s) Secretaria(s) requisitante(s) deverá proceder à validação dos itens, observando obrigatoriamente os seguintes parâmetros:\n\n(a) Aspecto técnico-descritivo: Verificar se o item cotado atende integralmente à necessidade descrita na requisição e no Termo de Referência, confirmando a compatibilidade técnica, características essenciais e especificações mínimas. A validação deverá ser expressamente declarada no despacho.\n\n(b) Aspecto de preço: Quando houver condições técnicas e elementos suficientes para avaliação do valor apresentado, a Secretaria deverá validar o preço, manifestando-se quanto à compatibilidade com o mercado e a adequação ao objeto. Caso não haja capacidade técnica para análise de preço, a Secretaria deverá DECLARAR EXPRESSAMENTE no despacho tal impossibilidade, mantendo, contudo, a validação apenas quanto ao aspecto técnico-descritivo.\n\nApós a validação, a Secretaria deverá juntar o despacho aos autos e retornar o processo ao Departamento de Compras, para as providências subsequentes, no prazo de até ${data.prazo || "___"} dias.`,
    },
    lancamento_sistema: {
        title: "Despacho – Solicitação de Lançamento no Sistema",
        template: (data) => `Considerando a análise pelos interessados conforme Despacho ${data.numDespacho || "___"}, o interesse das Secretaria(s) na aquisição dos itens constantes no Termo de Referência, o término da pesquisa de preço, e por fim, a Circular 245/2025 - Novo fluxo de tramitação dos processos de solicitação de compras, solicitamos as interessadas o devido lançamento dos itens no sistema, já vinculando à dotação orçamentária correspondente.\n\nLembrando que a Secretaria que tiver maior quantidade de itens lança das demais.\n\nApós o lançamento, solicitamos retorno para esta Divisão no prazo de até ${data.prazo || "___"} dias.`,
    },
    ausencia_resposta: {
        title: "Despacho – Ausência de Resposta da Secretaria",
        template: (data) => `Considerando a ausência de resposta ao Despacho ${data.numDespacho || "___"}, entendendo-se assim o aceite por parte da secretaria interessada, aliado ao interesse e urgência na aquisição dos itens constantes no Termo de Referência e o término da pesquisa de preço, e por fim, considerando a Circular 245/2025 - Novo fluxo de tramitação dos processos de solicitação de compras, solicitamos as interessadas o devido lançamento dos itens no sistema, já vinculando à dotação orçamentária correspondente.\n\nApós o lançamento, retornar para análise quanto aos lançamentos no prazo de até ${data.prazo || "___"} dias.`,
    },
};
